version: "3"
# docker run -d -p 6001:6001 -v /app/microservice:/data --network wsh_net --name ms01 wsh_docker:1.6
services:
  ms01:
    image: wsh_docker:1.6
    container_name: ms01
    ports:
      - "6001:6001"
    volumes:
      - /app/microservice:/data
    networks:
      - wsh_net
    depends_on:
      - redis
      - mysql
  # docker run -d -p 6379:
  redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
    volumes:
      - /app/redis/redis.conf:/etc/redis/redis.conf
      - /app/redis/data:/data
    networks:
      - wsh_net
    command: redis-server /etc/redis/redis.conf

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "db2021"
      MYSQL_USER: "wsh"
      MYSQL_PASSWORD: "wsh123"
    ports:
      - "3306:3306"
    volumes:
      - /app/mysql/db:/var/lib/mysql
      - /app/mysql/conf/my.cnf:/etc/my.cnf
      - /app/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wsh_net
      # 解決外部連線
    command: --default-authentication-plugin=mysql_native_password

networks:
  wsh_net:
